version: 1
builder:
  configs:
  - platform: linux
    swift_version: '5.5'
    image: registry.gitlab.com/finestructure/spi-images:basic-5.5-latest
  - platform: linux
    swift_version: '5.6'
    image: registry.gitlab.com/finestructure/spi-images:basic-5.6-latest
