disabled_rules:
  - type_name

line_length:
  warning: 150

included:
  - Sources
excluded:
  - Sources/SwiftCrossUI/ViewGraph/ViewGraphNodeChildren.swift
  - Sources/SwiftCrossUI/Builders/ViewContentBuilder.swift
  - Sources/SwiftCrossUI/Views/ViewContent.swift
