disabled_rules:
  - type_name
  - identifier_name
  - switch_case_alignment
  - cyclomatic_complexity # Too many false alarms for enum conversion switch statements
  - redundant_optional_initialization
  - closure_parameter_position
  - opening_brace
  - nesting # Sometimes it just makes sense to nest 2 levels deep
  - trailing_comma # Conflicts with swift-format

line_length: 140
type_body_length: 400

included:
  - Sources
  - Examples
excluded:
  - Sources/SwiftCrossUI/ViewGraph/ViewGraphNodeChildren.swift
  - Sources/SwiftCrossUI/Builders/ViewContentBuilder.swift
  - Sources/SwiftCrossUI/Views/ViewContent.swift
