name: Build macOS

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-13
    steps:
    - name: Force Xcode 14.3
      run: sudo xcode-select -switch /Applications/Xcode_14.3.app
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: brew install pkg-config gtk4
    - name: Patch libffi
      run: sed -i '' 's/-I..includedir.//g' /usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/13/libffi.pc
    - name: Build
      run: |
        swift build --target SwiftCrossUI && \
        swift build --target GtkBackend && \
        swift build --target CounterExample && \
        swift build --target ControlsExample && \
        swift build --target RandomNumberGeneratorExample && \
        swift build --target WindowPropertiesExample && \
        swift build --target GreetingGeneratorExample && \
        swift build --target FileViewerExample && \
        swift build --target NavigationExample && \
        swift build --target SplitExample && \
        swift build --target GtkCodeGen && \
        swift build --target GtkExample
    - name: Test
      run: swift test
