name: Build Windows

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Install Swift 5.8
      uses: compnerd/gha-setup-swift@main
      with:
        branch: swift-5.8-release
        tag: 5.8-RELEASE
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: vcpkg install --triplet x64-windows
    - name: Build
      env:
        PKG_CONFIG_PATH: ${{ github.workspace }}/vcpkg_installed/x64-windows/lib/pkgconfig
      run: swift build -v
