name: Build Windows

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
    - name: Install Dependencies
      run: vcpkg install --triplet x64-windows
    - name: Build
      env:
        PKG_CONFIG_PATH: ${{ env.GITHUB_WORKSPACE }}/vcpkg_installed/x64-windows/lib/pkgconfig
      run: swift build -v
