name: Build Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
    # If you'd rather use a certain version, format it like this: (5.5.3 is the latest as of writing)
    #- uses: fwal/setup-swift@v1
      #with:
        #swift-version: "5.5.3"
    - name: Install Dependencies
      run: |
        sudo apt update && \
        sudo apt install -y libgtk-3-dev clang
    - name: Build
      run: swift build -v
    #- name: Run tests
      #run: swift test -v