name: Update Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
    - name: Install Dependencies
      run: |
        sudo apt update && \
        sudo apt install -y libgtk-3-dev clang
    - name: Prepare Repository
      run: |
        cd /home/runner/work/swift-cross-ui
        git config --global user.email "58050615+NinjaCheetah@users.noreply.github.com"
        git config --global user.name "NinjaCheetah"
        git clone --depth 1 https://${{ secrets.ACTIONS_TOKEN }}@github.com/NinjaCheetah/swift-cross-ui.git gh-pages
        cd /home/runner/work/swift-cross-ui
        git checkout -b gh-pages
        git fetch && git pull
    - name: Compile Docs
      run: |
        export DOCC_JSON_PRETTYPRINT="YES"

        export SWIFTPM_ENABLE_COMMAND_PLUGINS=1 

        cd /home/runner/work/swift-cross-ui/swift-cross-ui

        swift package \
          --allow-writing-to-directory gh-pages/docs \
          generate-documentation \
          --target SwiftCrossUI \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path swift-cross-ui \
          --output-path /home/runner/work/swift-cross-ui/gh-pages/docs

        cd /home/runner/work/swift-cross-ui/gh-pages
        git stage .
        git commit -m "Update docs"
        git push
        