name: Update Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
    - name: Prepare Repository
      run: |
        git config --global user.email "58050615+NinjaCheetah@users.noreply.github.com"
        git config --global user.name "NinjaCheetah"
        git clone --depth 1 https://${{ secrets.ACTIONS_TOKEN }}@github.com/NinjaCheetah/swift-cross-ui.git
    - name: Compile Docs
      run: |
        set -eu
        filepath() {
          [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
        }

        SWIFT_DOCC_PLUGIN_ROOT="$(dirname $(dirname $(filepath $0)))"

        cd "$SWIFT_DOCC_PLUGIN_ROOT"

        export DOCC_JSON_PRETTYPRINT="YES"

        export SWIFTPM_ENABLE_COMMAND_PLUGINS=1 
        swift package \
          --allow-writing-to-directory gh-pages/docs \
          generate-documentation \
          --target SwiftCrossUI \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path swift-cross-ui \
          --output-path gh-pages/docs

        cd gh-pages
        git stage .
        git commit -m "Update docs"
        git push origin gh-pages
        